### ISSUE TITLE
字體可以不要用新細明體嗎

### ISSUE THREAD

**Issue by wotupset** [ShawTim/buddha-style#1]
![default](https://user-images.githubusercontent.com/4385327/39657921-67d09306-503f-11e8-9ace-953498f2a507.png)

如圖  
新細明體好醜

**Comment by ShawTim** [comment]
我沒有刻意使用新細明體
現在使用的是作業系統/瀏覽原生的預設字體
在你的情況下可能就是新細明體

我晚點把字體CSS搞一搞

沒錯，新細明體真的好醜

**Comment by ShawTim** [comment]
我把字體設定成一堆OS有預設安裝的字體，應該是可以的了， @wotupset 你可以再試試看
